### ISSUE TITLE
Limbo de comparação

### ISSUE THREAD

**Issue by pedroilidio** [gjvnq/LabIFSC#1]
Sugiro explicitar o caso em que a comparação de medidas pelo critério estabelecido resulta indeterminação:

2*(m1.incerteza + m2.incerteza) <= abs(m1.nominal - m2.nominal) < 3*(m1.incerteza + m2.incerteza)

Proceder-se-ia adicionando retorno extra aos operadores booleanos quando o caso acima for presente, de forma que estes  passem a retornar 0, 1 ou -1, ou algo do gênero.

**Comment by gjvnq** [comment]
Isso já é explicado no terceiro parágrafo e no segundo exemplo da seção Comparação do [README](https://github.com/gjvnq/LabIFSC#compara%C3%A7%C3%B5es).
