### ISSUE TITLE
Medida().unidade

### ISSUE THREAD

**Issue by pedroilidio** [gjvnq/LabIFSC#11]
Obter a string que representa a unidade de uma Medida. Isso é útil para se criar uma Medida a partir de outra, principalmente na definição de funções genéricas. Por exemplo, para retornar o coeficiente angular do fitting dos mínimos quadrados com o desvio padrão como incerteza tive que usar o seguinte (nos comentários explico como gostaria de fazer):

```
lin = linearize(xs, ys, imprimir=False)
a, b, dy, da, db = lin.values()

if usar_incerteza_estatistica:
        #implementar:
        #A = Medida((a.nominal, da.nominal), a.unidade)

        A = Medida((a.nominal, da.nominal))
        A.dimensao = a.dimensao
        A.unidades_originais = a.unidades_originais
```

**Comment by pedroilidio** [comment]
Mais tarde pretendo trabalhar nessas coisas, mas ando sem tempo.

**Comment by gjvnq** [comment]
Implementado na versão v0.1.10
