### ISSUE TITLE
Converter unidades automaticamente em expressões

### ISSUE THREAD

**Issue by pedroilidio** [gjvnq/LabIFSC#4]
Converter objetos de mesma grandeza às mesmas unidades (SI por padrão?) ao executar expressões.

**Comment by gjvnq** [comment]
De acordo com o README:

> As contas de soma e subtração sempre ficam nas unidades do primeiro argumento nas operações, exceto quando o primeiro argumento for adimensional. Neste caso, as unidades serão as do segundo argumento.
> 
> Já as contas de multiplicação e divisão simplesmente combinam as unidades.
