### ISSUE TITLE
Propagação de erro para potência

### ISSUE THREAD

**Issue by felipelincoln** [gjvnq/LabIFSC#7]
A^B, sendo A e B uma Medida ainda não está implantado.

**Comment by gjvnq** [comment]
Isso é meio qie intencional já que a unidade não fica bem definida. Ex: (2
metros)^(3 segundos) = (8 metro^segundo) ? (8 metro^3) ?

**Comment by felipelincoln** [comment]
Entendo seu ponto. Mas esses expoentes serão sempre adimensionais, por exemplo: A^n, sendo n = M((1,0.1)). 
Na prática de lab3 estávamos trabalhando com o fator eta de diodos, que aparecem num expoente na eq. de Shockely, obtive esse valor fittando a curva e para poder usar o valor encontrado usei a uma formula que achei no wiki para a propagação : https://en.wikipedia.org/wiki/Propagation_of_uncertainty#Example_formulas

**Comment by gjvnq** [comment]
Resolvido na versão v0.1.9

**Comment by pedroilidio** [comment]
A fórmula utilizada para propagação da incerteza não admite valores negativos para a base da potência, dado que o domínio do logarítmo natural é (0, +oo). Vide Issue #16 .
